# Generated by Django 3.2.8 on 2021-10-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211011_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscompany',
            name='route',
            field=models.ManyToManyField(default='', to='core.Route'),
        ),
    ]
