# Generated by Django 3.2.8 on 2021-10-11 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_buscompany_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('available_seat', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('license_number', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='buscompany',
            name='route',
        ),
        migrations.AddField(
            model_name='buscompany',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='buscompany',
            name='market_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='buscompany',
            name='bus_name',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buses')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='buses',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buscompany'),
        ),
        migrations.AddField(
            model_name='buses',
            name='route',
            field=models.ManyToManyField(default='', to='core.Route'),
        ),
        migrations.AddField(
            model_name='buses',
            name='stuff',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buscompany',
            name='bus_name',
            field=models.ManyToManyField(default='', to='core.Buses'),
        ),
    ]
