# Generated by Django 3.2.8 on 2021-10-11 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211011_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buses',
            name='stuff',
        ),
        migrations.AddField(
            model_name='buses',
            name='stuff',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
