# Generated by Django 3.2.8 on 2021-10-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ticket_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='validity',
            field=models.BooleanField(default=True),
        ),
    ]
