# Generated by Django 3.2.8 on 2021-10-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ticket_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='seat_each_row',
            field=models.IntegerField(default=0),
        ),
    ]
