# Generated by Django 3.2.8 on 2021-10-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211011_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
