# Generated by Django 3.2.8 on 2021-10-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
    ]
