# Generated by Django 3.2.8 on 2021-10-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_route_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buscompany',
            name='bus_name',
        ),
    ]
