# Generated by Django 3.2.8 on 2021-10-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_buscompany_bus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buses',
            name='route',
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_routes', models.ManyToManyField(to='core.Route')),
            ],
        ),
    ]
