# Generated by Django 3.2.8 on 2021-10-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20211011_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buses',
            new_name='Bus',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('bus_at_now', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
                ('bus_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bus')),
            ],
        ),
    ]
