# Generated by Django 3.2.8 on 2021-10-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20211012_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['station_serial']},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='trip_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
