# Generated by Django 3.2.8 on 2021-11-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_timeslot_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ManyToManyField(to='core.TimeSlot')),
            ],
        ),
    ]
