# Generated by Django 3.2.8 on 2021-11-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_routedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
