# Generated by Django 3.2.8 on 2021-11-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('time', models.TimeField()),
            ],
        ),
    ]
