# Generated by Django 3.2.8 on 2021-11-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_ticket_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created']},
        ),
    ]
