# Generated by Django 3.2.8 on 2021-11-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_applyhalf_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyhalf',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
