# Generated by Django 3.2.8 on 2021-11-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_applyhalf_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileup',
            old_name='file',
            new_name='files',
        ),
    ]
