# Generated by Django 3.2.8 on 2021-11-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_file_fileup_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='busname',
            field=models.CharField(default='', max_length=500),
        ),
    ]
