# Generated by Django 3.2.8 on 2021-11-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_review_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created']},
        ),
    ]
