# Generated by Django 3.2.8 on 2021-11-18 08:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
    ]
