# Generated by Django 3.2.8 on 2021-11-18 08:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_announcement_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
